const ScanRecord = require('../models/ScanRecord');
const PDFDocument = require('pdfkit');

/* ────────────────────────────────────────────────────────────────
   GET /api/history
   Query params: page, limit, status, search
──────────────────────────────────────────────────────────────── */
exports.getHistory = async (req, res, next) => {
  try {
    const page   = Math.max(1, parseInt(req.query.page)  || 1);
    const limit  = Math.min(50, parseInt(req.query.limit) || 10);
    const skip   = (page - 1) * limit;

    const filter = { userId: req.user._id };
    if (req.query.status && req.query.status !== 'ALL') {
      filter.result = req.query.status;
    }
    if (req.query.search) {
      filter.filename = { $regex: req.query.search, $options: 'i' };
    }

    const [records, total] = await Promise.all([
      ScanRecord.find(filter)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .select('-gradcamBase64 -rawResponse')   // keep response lean
        .lean(),
      ScanRecord.countDocuments(filter),
    ]);

    res.json({ records, total, page, limit });
  } catch (err) {
    next(err);
  }
};

/* ────────────────────────────────────────────────────────────────
   GET /api/history/:id/report
   Streams a PDF diagnostic report for one scan record.
──────────────────────────────────────────────────────────────── */
exports.getReport = async (req, res, next) => {
  try {
    const record = await ScanRecord.findOne({
      _id:    req.params.id,
      userId: req.user._id,          // users can only fetch their own records
    }).lean();

    if (!record) return res.status(404).json({ message: 'Record not found' });

    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="TB-Report-${record._id}.pdf"`
    );
    doc.pipe(res);

    /* ── Header ── */
    doc
      .fontSize(22).font('Helvetica-Bold').fillColor('#1a1a2e')
      .text('TB Detection Diagnostic Report', { align: 'center' })
      .moveDown(0.3);

    doc
      .fontSize(10).font('Helvetica').fillColor('#6b7280')
      .text('Generated by TB Detection AI System  ·  For research use only', { align: 'center' })
      .moveDown(1.5);

    /* ── Divider ── */
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke().moveDown(1);

    /* ── Result badge area ── */
    const resultColor =
      record.result === 'TB_DETECTED'  ? '#ef4444' :
      record.result === 'NORMAL'       ? '#22c55e' : '#f59e0b';

    doc
      .fontSize(13).font('Helvetica-Bold').fillColor('#111827')
      .text('Prediction Result', { continued: false })
      .moveDown(0.4);

    doc
      .fontSize(18).font('Helvetica-Bold').fillColor(resultColor)
      .text((record.result || 'INCONCLUSIVE').replace('_', ' '), { indent: 0 })
      .moveDown(0.3);

    doc
      .fontSize(11).font('Helvetica').fillColor('#374151')
      .text(`Confidence: ${Math.round((record.confidence || 0) * 100)}%`)
      .moveDown(1.5);

    /* ── Details table ── */
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke().moveDown(0.8);

    const rows = [
      ['Scan ID',          record._id.toString()],
      ['Patient ID',       record.patientId || 'Not specified'],
      ['Filename',         record.filename],
      ['Model version',    record.modelVersion || 'ResNet-50 v1'],
      ['Processing time',  record.processingMs ? `${record.processingMs} ms` : '—'],
      ['Scan date',        new Date(record.createdAt).toLocaleString()],
      ['Report generated', new Date().toLocaleString()],
    ];

    rows.forEach(([label, value]) => {
      doc
        .fontSize(10).font('Helvetica-Bold').fillColor('#6b7280')
        .text(label, 50, doc.y, { width: 160, continued: true })
        .font('Helvetica').fillColor('#111827')
        .text(value, { width: 335 })
        .moveDown(0.4);
    });

    /* ── Grad-CAM image (if stored as base64) ── */
    if (record.gradcamBase64) {
      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke().moveDown(0.8);
      doc.fontSize(13).font('Helvetica-Bold').fillColor('#111827').text('Grad-CAM Heatmap').moveDown(0.5);

      const imgBuffer = Buffer.from(record.gradcamBase64, 'base64');
      try {
        doc.image(imgBuffer, { fit: [400, 300], align: 'center' });
      } catch (_) {
        doc.fontSize(10).fillColor('#6b7280').text('(Heatmap could not be rendered)');
      }
    }

    /* ── Disclaimer ── */
    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke().moveDown(0.8);
    doc
      .fontSize(9).font('Helvetica').fillColor('#9ca3af')
      .text(
        '⚠ DISCLAIMER: This report is generated by an AI system for research and educational purposes only. ' +
        'It is NOT a certified medical diagnosis. Do not use as a substitute for professional medical judgment. ' +
        'Always consult a qualified healthcare professional.',
        { align: 'justify' }
      );

    doc.end();
  } catch (err) {
    next(err);
  }
};